# **Inteligencia Artificial con Aplicaciones en Economía I**

- 👩‍🏫 **Profesora:** [Lina María Castro](https://www.linkedin.com/in/lina-maria-castro)  
- 📧 **Email:** [lmcastroco@gmail.com](mailto:lmcastroco@gmail.com)  
- 🎓 **Universidad:** Universidad Externado de Colombia - Facultad de Economía

# **Taller Limpieza y transformación de datos**🧹

**IMPORTANTE**: Guarda una copia de este notebook en tu Google Drive o computador.

**Taller en parejas.**

**Nombres estudiantes:**

Maria Paula Caro
-Juan Manuel Vellaizan

**Forma de entrega:**

- Nombrar el archivo de la siguiente forma:“Taller_Limpieza_apellidos.ipynb”.
- Suba el Jupyter Notebook a su cuenta en Github y envíe el link en el siguiente Forms: https://forms.cloud.microsoft/r/8Qw28N1t1j.

**IMPORTANTE:** No se recibirán talleres en Google Colab, el notebook debe estar subido en Github.

**Plazo de entrega:**

10 de septiembre de 2026, máximo a las 11:59 p.m. Tenga en cuenta que luego de esa hora el formulario en forms se cierra. El Jupupyter Notebook también debe quedar subido en Github antes de esa hora.

**Instrucciones Generales:**

Completa el código en las celdas marcadas con `### TU CÓDIGO AQUÍ ###`. Puedes añadir más celdas si lo requieres.

Utilice la base de la GEIH de enero a junio de 2026, la cual se encuentra en el repositorio en Github del curso o en Google Drive en la carpeta "datasets". Tenga en cuenta sep=";" y encoding='latin-1'. Las variables 'DPTO' y 'RAMA4D_R4' deben ser cargadas como string.

# Ejercicio 1: Importar librerías y cargar datos

1.	Importe todas las librerías que vaya a utilizar.

In [ ]:
### TU CÓDIGO AQUÍ ###
import pandas as pd
import numpy as np

2.	Mejore la visualización de los dataframes como se ha visto en clase.

In [ ]:
### TU CÓDIGO AQUÍ ###
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.width', None)

3.	Conéctese a su Google Drive y establezca la ruta del dataset.

In [ ]:
### TU CÓDIGO AQUÍ ###
from google.colab import drive
drive.mount('/content/drive')

ruta = '/content/drive/MyDrive/datasets/GEIH_2026_Ene_Jun_Consolidado.csv'

Mounted at /content/drive

4.	Cargue los datos en el notebook. Llame al dataframe 'df_geih'

In [ ]:
### TU CÓDIGO AQUÍ ###

df_geih = pd.read_csv(ruta, sep=';', encoding='latin-1', dtype={'DPTO': str, 'RAMA4D_R4': str})

/tmp/ipykernel_2947/2462314479.py:3: DtypeWarning: Columns (74,89,102,110,116,134,138,188,210,260,263,267,269,272,274,283,304) have mixed types. Specify dtype option on import or set low_memory=False.
  df_geih = pd.read_csv(ruta, sep=';', encoding='latin-1', dtype={'DPTO': str, 'RAMA4D_R4': str})

5. Obtenga las dimensiones de la base

In [ ]:
### TU CÓDIGO AQUÍ ###
df_geih.shape

(401950, 322)

# Ejercicio 2:  Seleccionar y renombrar columnas

La GEIH contiene cientos de variables. Para nuestro análisis del mercado laboral, nos enfocaremos en un subconjunto.

Adicionalmente, los nombres de las columnas en la GEIH son códigos. Para hacer el análisis más intuitivo, vamos a renombrarlas.

1. Crea un nuevo DataFrame llamado `df_empleo` que contenga únicamente las columnas que están en la lista `columnas_interes`.

In [ ]:
columnas_interes = ['DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'MES', 'CLASE', 'DPTO', 'FEX_C18', 'PT', 'P3271', 'P6040', 'P6080', 'P3043', 'OCI',
                    'P6430', 'RAMA4D_R4', 'INGLABO', 'DESCRIPCION_CIIU', 'NOMBRE_DPTO']

In [ ]:
### TU CÓDIGO AQUÍ ###

df_empleo = df_geih[columnas_interes]

2. Renombra las columnas del DataFrame `df_empleo` utilizando el diccionario `mapa_nombres`.

In [ ]:
mapa_nombres = {
'DIRECTORIO': 'id_vivienda',
'SECUENCIA_P': 'id_hogar',
'ORDEN': 'id_persona',
'MES': 'mes',
'CLASE': 'clase',
'DPTO': 'departamento',
'FEX_C18': 'factor_expansion',
'PT': 'poblacion_total',
'P3271': 'sexo',
'P6040': 'edad',
'P6080': 'grupo_etnico',
'P3043': 'nivel_educativo',
'OCI': 'ocupados',
'P6430': 'categoria_ocupacional',
'RAMA4D_R4': 'cod_ciiu',
'INGLABO': 'ingreso_laboral',
'DESCRIPCION_CIIU': 'desc_ciiu',
'NOMBRE_DPTO': 'nombre_dpto'}

In [ ]:
### TU CÓDIGO AQUÍ ###

df_empleo = df_empleo.rename(columns=mapa_nombres)

3. Obtenga las dimensiones de la base

In [ ]:
### TU CÓDIGO AQUÍ ###

df_empleo.shape

(401950, 18)

# Ejercicio 3: Revisión de duplicados

Un paso crucial en la limpieza es asegurar que no haya observaciones duplicadas que puedan sesgar nuestro análisis.

1. Verifica si hay filas duplicadas en `df_empleo`.

In [ ]:
### TU CÓDIGO AQUÍ ###

df_empleo.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
401945    False
401946    False
401947    False
401948    False
401949    False
Length: 401950, dtype: bool

2. Cuenta cuántas filas duplicadas existen.

In [ ]:
### TU CÓDIGO AQUÍ ###

df_empleo.duplicated().sum()

np.int64(0)

3. Elimina las filas duplicadas, si las hay.

In [ ]:
### TU CÓDIGO AQUÍ ###

df_empleo = df_empleo.drop_duplicates()

4. Verifica si hay filas duplicadas específicamente en las columnas 'id_vivienda'. Si hay duplicados, explica por qué existen estos duplicados en la GEIH para esta columna.

In [ ]:
### TU CÓDIGO AQUÍ ###

df_empleo.duplicated(subset=['id_vivienda']).sum()

np.int64(256630)

# Ejercicio 4: Valores faltantes

Los datos del mundo real raramente están completos. Aquí, trataremos los valores faltantes en la columna de ingresos.

1. Calcula el número de valores nulos (`NaN`) en la columna `ingreso_laboral` **antes** de cualquier modificación.

In [ ]:
### TU CÓDIGO AQUÍ ###

df_empleo['ingreso_laboral'].isna().sum()

np.int64(228153)

2. En la GEIH, un ingreso faltante a menudo significa que la persona no reportó ingresos o no aplica (ej. no trabaja). Una estrategia común es imputar estos valores con `0`. Rellena los valores `NaN` en la columna `ingreso_laboral` con `0`.

In [ ]:
### TU CÓDIGO AQUÍ ###

df_empleo['ingreso_laboral'] = df_empleo['ingreso_laboral'].fillna(0)

# Ejercicio 5: Decodificar variables

Las variables categóricas a menudo necesitan ser "traducidas" para hacerlas más entendibles para el análisis.

1. Usa los siguientes diccionarios para reemplazar los códigos numéricos por etiquetas de texto en las siguientes columnas: 'clase', 'sexo', 'grupo_etnico', 'nivel_educativo' y 'categoria_ocupacional'. Muestra los conteos de las nuevas categorías usando `.value_counts()` para verificar el cambio en cada una de las columnas.

In [ ]:
dic_clase = {1: 'Cabeceras', 2: 'Centros poblados y rural disperso'}
dic_sexo = {1: 'Hombre', 2: 'Mujer'}
dic_etnico = {1: 'Indígena', 2: 'Gitano (Rom)', 3: 'Raizal del archipiélago', 4: 'Palenquero',
              5: 'Negro, mulato (afrodescendiente)', 6: 'Ninguno de los anteriores'}
dic_nivel_educativo = {1: 'Ninguno', 2: 'Educación media', 3: 'Educación media',
                       4: 'Educación media', 5: 'Técnica profesional', 6: 'Tecnológica',
                       7: 'Universitaria', 8: 'Especialización', 9: 'Maestría',
                       10: 'Doctorado', 99: 'No sabe, no informa'}
dic_cat_ocu = {1: 'Asalariado', 2: 'Asalariado', 3: 'Asalariado',
               8: 'Asalariado', 4: 'Independiente', 5: 'Independiente',
               9: 'Independiente', 6: 'Trabajador sin remuneración',
               7: 'Trabajador sin remuneración'}

In [ ]:
### TU CÓDIGO AQUÍ ###

df_empleo['clase'] = df_empleo['clase'].map(dic_clase)
df_empleo['clase'].value_counts()

clase
Cabeceras                            348316
Centros poblados y rural disperso     53634
Name: count, dtype: int64

In [ ]:
### TU CÓDIGO AQUÍ ###

df_empleo['sexo'] = df_empleo['sexo'].map(dic_sexo)
df_empleo['sexo'].value_counts()

sexo
Mujer     214629
Hombre    187321
Name: count, dtype: int64

In [ ]:
### TU CÓDIGO AQUÍ ###

df_empleo['grupo_etnico'] = df_empleo['grupo_etnico'].map(dic_etnico)
df_empleo['grupo_etnico'].value_counts()

grupo_etnico
Ninguno de los anteriores           345317
Negro, mulato (afrodescendiente)     35191
Indígena                             20331
Raizal del archipiélago                971
Palenquero                              90
Gitano (Rom)                            50
Name: count, dtype: int64

In [ ]:
### TU CÓDIGO AQUÍ ###

df_empleo['nivel_educativo'] = df_empleo['nivel_educativo'].map(dic_nivel_educativo)
df_empleo['nivel_educativo'].value_counts()

nivel_educativo
Educación media        114830
Universitaria           35105
Técnica profesional     24188
Ninguno                 12408
Tecnológica             10651
Especialización          9618
Maestría                 4091
Doctorado                 423
Name: count, dtype: int64

In [ ]:
### TU CÓDIGO AQUÍ ###
df_empleo['categoria_ocupacional'] = df_empleo['categoria_ocupacional'].map(dic_cat_ocu)
df_empleo['categoria_ocupacional'].value_counts()

categoria_ocupacional
Asalariado                     90891
Independiente                  79620
Trabajador sin remuneración     6684
Name: count, dtype: int64

# Ejercicio 6: Reorganizar columnas

1. Reorganiza las columnas con el siguiente orden: 'id_vivienda', 'id_hogar', 'id_persona', 'mes', 'clase', 'departamento', 'nombre_dpto',     'factor_expansion', 'poblacion_total', 'sexo', 'edad', 'grupo_etnico', 'nivel_educativo', 'ocupados', 'categoria_ocupacional', 'cod_ciiu', 'desc_ciiu', 'ingreso_laboral'

In [ ]:
### TU CÓDIGO AQUÍ ###

orden_columnas = ['id_vivienda', 'id_hogar', 'id_persona', 'mes', 'clase', 'departamento', 'nombre_dpto',
                   'factor_expansion', 'poblacion_total', 'sexo', 'edad', 'grupo_etnico', 'nivel_educativo',
                   'ocupados', 'categoria_ocupacional', 'cod_ciiu', 'desc_ciiu', 'ingreso_laboral']
df_empleo = df_empleo[orden_columnas]

# Ejercicio 7: Cambiar tipo de dato

Para realizar cálculos y análisis correctamente, las columnas deben tener el tipo de dato adecuado (numérico, categórico, etc.).

1.  Muestra en pantalla los tipos de datos actuales de `df_empleo`.

In [ ]:
### TU CÓDIGO AQUÍ ###

df_empleo.dtypes

id_vivienda                int64
id_hogar                   int64
id_persona                 int64
mes                        int64
clase                     object
departamento              object
nombre_dpto               object
factor_expansion         float64
poblacion_total            int64
sexo                      object
edad                       int64
grupo_etnico              object
nivel_educativo           object
ocupados                 float64
categoria_ocupacional     object
cod_ciiu                  object
desc_ciiu                 object
ingreso_laboral          float64
dtype: object

2.  Las siguientes columnas representan categorías: 'clase', 'departamento', 'nombre_dpto', 'sexo', 'grupo_etnico', 'nivel_educativo', 'categoria_ocupacional', 'cod_ciiu', 'desc_ciiu'. Conviértelas al tipo `category` para optimizar el uso de memoria y facilitar análisis futuros.

In [ ]:
### TU CÓDIGO AQUÍ ###

columnas_categoricas = ['clase', 'departamento', 'nombre_dpto', 'sexo', 'grupo_etnico',
                          'nivel_educativo', 'categoria_ocupacional', 'cod_ciiu', 'desc_ciiu']
df_empleo[columnas_categoricas] = df_empleo[columnas_categoricas].astype('category')

# Ejercicio 8: Ordenar el dataframe (5%)

1. Ordena el dataframe por la columna "edad" de mayor a menor. Observa la columna 'edad' y escribe en una celda de markdown cuál fue la edad mínima y la edad máxima de las personas que respondieron la encuesta de la GEIH.

In [ ]:

### TU CÓDIGO AQUÍ ###
df_empleo = df_empleo.sort_values(by='edad', ascending=False)
df_empleo[['edad']].describe()

                edad
count  401950.000000
mean       36.554930
std        22.250976
min         0.000000
25%        18.000000
50%        35.000000
75%        54.000000
max       107.000000

Escribe tu análisis aquí:

# Ejercicio 9: Groupby

Agrupar los datos por categorías, nos permite realizar análisis más profundos y obtener insights valiosos, que a simple vista no vemos en la base de datos.

1. Crea un nuevo dataframe llamado "df_sexo" donde se agrupe por 'sexo' y se calcule la suma de las columnas 'poblacion_total' y 'ocupados'. Crea una nueva columna que se llame 'porcentaje_ocupados' donde dividas las columna 'ocupados' sobre 'poblacion_total'. Al final usa reset_index() para convertir las categorías de sexo en una columna.

In [ ]:
### TU CÓDIGO AQUÍ ###

df_empleo = df_empleo.sort_values(by='edad', ascending=False)
df_empleo['edad'].describe()

count    401950.000000
mean         36.554930
std          22.250976
min           0.000000
25%          18.000000
50%          35.000000
75%          54.000000
max         107.000000
Name: edad, dtype: float64

2. Crea un nuevo dataframe llamado "df_educacion" donde se agrupe por 'nivel_educativo' y se calcule la suma de las columnas 'poblacion_total' y 'ocupados'. Crea una nueva columna que se llame 'porcentaje_ocupados' donde dividas las columna 'ocupados' sobre 'poblacion_total'. Al final usa reset_index() para convertir las categorías de nivel educativo en una columna.

In [ ]:
### TU CÓDIGO AQUÍ ###

df_sexo = df_empleo.groupby('sexo')[['poblacion_total', 'ocupados']].sum()
df_sexo['porcentaje_ocupados'] = df_sexo['ocupados'] / df_sexo['poblacion_total']
df_sexo = df_sexo.reset_index()

/tmp/ipykernel_2947/959162925.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_sexo = df_empleo.groupby('sexo')[['poblacion_total', 'ocupados']].sum()

3. En una celda de Markdown escribe qué conclusiones puedes sacar de la información obtenida en df_sexo y df_educacion.

Escribe tu análisis aquí:

# Ejercicio 10: Filtrar datos

1. A partir de df_empleo, crea el DataFrame `df_ing` con observaciones donde `ingreso_laboral` no sea nulo y además sea mayor estrictamente al salario mínimo para 2026 (con subsidio de transporte).

In [ ]:
### TU CÓDIGO AQUÍ ###

salario_minimo_2026 = 2000000
df_ing = df_empleo[(df_empleo['ingreso_laboral'].notna()) & (df_empleo['ingreso_laboral'] > salario_minimo_2026)]

2. ¿Cuántas personas tienen un salario estrictamente mayor al salario mínimo?

In [ ]:
### TU CÓDIGO AQUÍ ###

len(df_ing)

50103

3. Crea el dataframe df_mujeres donde se encuentren solamente mujeres que están ubicadas en el departamento del Tolima, que son asalariadas y cuyo nivel educativo es educación media o superior.

In [ ]:
### TU CÓDIGO AQUÍ ###

niveles_media_superior = ['Educación media', 'Técnica profesional', 'Tecnológica', 'Universitaria',
                            'Especialización', 'Maestría', 'Doctorado']
df_mujeres = df_empleo[
    (df_empleo['sexo'] == 'Mujer') &
    (df_empleo['nombre_dpto'] == 'Tolima') &
    (df_empleo['categoria_ocupacional'] == 'Asalariado') &
    (df_empleo['nivel_educativo'].isin(niveles_media_superior))
]

4. ¿Cuáles son las dimensiones de df_mujeres?

In [ ]:
### TU CÓDIGO AQUÍ ###

df_mujeres.shape

(0, 18)